nodeLinker: node-modules

packageExtensions:
  "@remix-run/dev@*":
    peerDependencies:
      react: ">=17"
      react-dom: ">=17"
  "@remix-run/express@*":
    peerDependencies:
      react: ">=17"
      react-dom: ">=17"
  "@remix-run/node@*":
    peerDependencies:
      react: ">=17"
      react-dom: ">=17"
  "@remix-run/serve@*":
    peerDependencies:
      react: ">=17"
      react-dom: ">=17"
  "@remix-run/vercel@*":
    peerDependencies:
      react: ">=17"
      react-dom: ">=17"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
