name: Build
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn lint
      - run: yarn prettier --check .

  ts:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn ts

  deploy-temp:
    name: Deploy to temp environment
    runs-on: ubuntu-latest
    needs: [lint, ts]
    steps:
      - name: Deploy
        uses: ./.github/actions/deploy

  integ:
    name: Integ tests
    runs-on: ubuntu-latest
    needs: [deploy-temp]
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn test:integ

  e2e:
    name: Integ tests
    runs-on: ubuntu-latest
    needs: [deploy-temp]
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn test:e2e
