name: Build
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn lint
      - run: yarn prettier --check .

  ts:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn ts

  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn test

  deploy:
    name: Deploy to prod environment
    runs-on: ubuntu-latest
    needs: [lint, ts, e2e]
    steps:
      - uses: actions/checkout@v1
      - run: yarn setup
      - run: flyctl
